// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDriwLJbdke06XQSct-eE3neBqDi-LIleQ',
    appId: '1:767002391981:web:b13dbf65924f3252435d24',
    messagingSenderId: '767002391981',
    projectId: 'shoppyist-ee379',
    authDomain: 'shoppyist-ee379.firebaseapp.com',
    storageBucket: 'shoppyist-ee379.appspot.com',
    measurementId: 'G-32FCWNKWEF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDaQTfytc173aV4suGc-B89_iGRYv17DNg',
    appId: '1:767002391981:android:dc841ed8ff987927435d24',
    messagingSenderId: '767002391981',
    projectId: 'shoppyist-ee379',
    storageBucket: 'shoppyist-ee379.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC40vwfpMaJASP0jTlE-gjO1-S7GkjVoN4',
    appId: '1:767002391981:ios:d78ddc15300a6a03435d24',
    messagingSenderId: '767002391981',
    projectId: 'shoppyist-ee379',
    storageBucket: 'shoppyist-ee379.appspot.com',
    iosClientId: '767002391981-9j82657tm0ecepdi75lq3rq9ap0rmmj4.apps.googleusercontent.com',
    iosBundleId: 'com.example.shoppyist',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC40vwfpMaJASP0jTlE-gjO1-S7GkjVoN4',
    appId: '1:767002391981:ios:d78ddc15300a6a03435d24',
    messagingSenderId: '767002391981',
    projectId: 'shoppyist-ee379',
    storageBucket: 'shoppyist-ee379.appspot.com',
    iosClientId: '767002391981-9j82657tm0ecepdi75lq3rq9ap0rmmj4.apps.googleusercontent.com',
    iosBundleId: 'com.example.shoppyist',
  );
}
